# Generated by Django 3.2.15 on 2022-09-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F1Drivers',
            fields=[
                ('number', models.IntegerField(db_column='Number', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('team', models.CharField(db_column='Team', max_length=50)),
                ('born', models.DateField(db_column='Born')),
                ('nationality', models.CharField(db_column='Nationality', max_length=50)),
            ],
            options={
                'db_table': 'f1_drivers',
            },
        ),
        migrations.CreateModel(
            name='F1StatsSoFar',
            fields=[
                ('number', models.OneToOneField(db_column='Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FormulaOne.f1drivers')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('wins', models.IntegerField(db_column='Wins')),
                ('points', models.IntegerField(db_column='Points')),
            ],
            options={
                'db_table': 'f1_stats_so_far',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('round', models.IntegerField(db_column='Round', primary_key=True, serialize=False)),
                ('country', models.CharField(db_column='Country', max_length=50)),
                ('date', models.DateField(db_column='Date')),
                ('champion', models.ForeignKey(blank=True, db_column='Champion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FormulaOne.f1drivers')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
